from django.urls import path
from .views_Abdulbosit import *

urlpatterns = [
    path("blank/", Pages_blank, name="blank"),
    path("sing_in/", Pages_sing_in, name="sing_in"),
    path("create_about/", Create_About, name="create_about"),
    path("create_information/", Create_information, name="create_information"),
    path("users/", Users, name="users"),
    path("search/", Search, name="search"),
    path("accepted/<int:pk>/", Accepted, name="accepted"),
    path("rejected/<int:pk>/", Rejected, name="rejected"),
    path("page_accepted/", Page_accepted, name="page_accepted"),
    path("page_rejected/", Page_rejected, name="page_rejected"),
    path("is_top/<int:pk>/", Is_top, name="is_top"),
    path("is_recommended/<int:pk>/", Is_recommended, name="is_recommended"),
    path("page_is_recommended/", Page_is_recommended, name="page_is_recommended"),
    path("page_is_top/", Page_is_top, name="page_is_top"),
    path("reklama/", Page_reklama, name="reklama"),
    path("page_about/", Page_about, name="page_about"),
    path("information/", Page_information, name="information"),
    path("delete_reklema/<int:pk>/", Delete_Reklama, name="delete_reklema"),
    path("change_reklama/<int:pk>/", Change_Reklama, name="change_reklama"),
    path("page_change_reklama/<int:pk>/", Page_Change_Reklama, name="page_change_reklama"),
    path("add_reklama/", Add_reklama, name="add_reklama"),
    path("page_add_reklama/", Page_Add_Reklama, name="page_add_reklama"),
    path("delete_about/<int:pk>/", Delete_about, name="delete_about"),
    path("page_category/", Page_category, name="page_category"),
    path("change_category/<int:pk>/", Change_category, name="change_category"),
    path("create_category/", Create_category, name="create_category"),
    path("delete_category/<int:pk>/", Delete_category, name="delete_category"),
    path("delete_information/<int:pk>/", Delete_information, name="delete_information"),
    path("change_information/<int:pk>/", Change_information, name="change_information"),
    path("change_about/<int:pk>/", Change_about, name="change_about")
]