# Generated by Django 4.1.1 on 2022-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'in working'), (2, 'delete')], default=1, null=True),
        ),
    ]
