# Generated by Django 4.0.5 on 2022-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklama',
            name='img',
            field=models.ImageField(default=1, upload_to='Reklama/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reklama',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reklama',
            name='status',
            field=models.IntegerField(choices=[(1, 'in work'), (2, 'deleted')], default=1),
        ),
    ]
