# Generated by Django 4.0.3 on 2022-10-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
