# Generated by Django 4.1.1 on 2022-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subcategory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'in working'), (2, 'delete')], default=1, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'in working'), (2, 'delete')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='district',
            field=models.ManyToManyField(to='main.district'),
        ),
    ]
