# Generated by Django 4.0.3 on 2022-10-24 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reklama_img_reklama_link_reklama_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklama',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
